### ISSUE TITLE
我发现了个问题,不知道是不是因为个人原因

### ISSUE THREAD

**Issue by tangchao0106** [wenmingvs/LogReport#63]
1,我用的小米手机5.02测试的,手机4G打开,进程序,程序不走protected void onHandleIntent(Intent intent) {断点,网络关闭后,再重新进去就走,我测试了10几遍都是这个问题.,这个手机这个方法CompressUtil.zipFileAtPath返回true是正确的,另外一个确实false

2有一个4.2.2的平板运行,程序       if (CompressUtil.zipFileAtPath(logfolder.getAbsolutePath(), zipfile.getAbsolutePath())) {方法中总是返回false,,错误原因java.io.FileNotFoundException: /sdcard/222tclog/AlreadyUploadLog/UploadOn2016-07-29 19:49:42:488.zip: open failed: EINVAL (Invalid argument)这个..

3 4.2.2那个平板zipFileAtPath方法中   FileOutputStream dest = new FileOutputStream(toLocation);
            ZipOutputStream out = new ZipOutputStream(new BufferedOutputStream(
                    dest));调试过不去
大神  请教你

**Comment by wenmingvs** [comment]
1. 请仔细阅读我的ReadMe说明，默认情况下移动网络不上传崩溃日志
2. 应该是文件目录创建失败了，一些国内的奇葩Android机型，或者root的手机，会存在无法创建多级目录的情况，多重启几下尝试一下。我之前有一台手机，是S7 edge，已经root了，有时候也存在这种情况
3. 这个问我我还没有研究过，应该和问题2是一样的，不存在这个文件路径，所以也就压缩失败了

请校验一下是否我的判断是否正确，再给我答复可以吗？

**Comment by tangchao0106** [comment]
大神,说的正确,我这个4.2.2的平板是公司定制的.估计是创建不了目录,没有品牌,,其他几个有牌子的暂时没有发现这个问题..,那没有解决方法了吗

刚看到github有我打印的日志了,但是,我自己的163邮箱,怎么一直没有收到,难道是我这个移动的网络发不出去吗,上次也是这个网络发不出去,测试的时候,没有收到邮件,回家换了家里的网络就可以正常收到了邮件了.

**Comment by tangchao0106** [comment]
补一句,是这个4.2.2的可以创建AlreadyUploadLog目录但进去里面是空的.怎么出错都不会有.zip出现

**Comment by wenmingvs** [comment]
1. 无解，底层做了限制了。尝试多重启几次试一下？我上回手机就是这个好的。
2. 我的设计就是，默认情况下移动网络不上传崩溃日志，所以不是你的移动网络问题，是我的功能就是这么设计的，为用户节省流量。如果你需要在wifi和移动流量情况下都发送邮件，请在初始化的时候设置 setWifiOnly(false)即可
3. 因为目录没有，所以日志文件的txt也无法生成了，日志的txt都没有，就不会有压缩包了

**Comment by tangchao0106** [comment]
关于网的事,可能误会了.反正在家里用宽度的wifi可以正常收邮件,,我现在在办公室,用的是移动的热点类似cmcc.把手机号和密码输入,然后笔记本用360wifi扩散出去,终端连接的笔记本的wifi.

不知道中间是不是有协议.这个网是算移动网络?还是WIF?I....所以说,现在一直没有收到邮件....调试的时候也走public void onSuceess() {
    LogUtil.d("日志发送成功！！");
    FileUtil.deleteDir(logfolder);

**Comment by wenmingvs** [comment]
都打发送成功的Log了，肯定是发送成功了。只有成功了才会回调这个方法的。你尝试去垃圾邮箱里面找找，是不是被归为垃圾邮件了。我有一回也遇到这种情况
