### ISSUE TITLE
我用你的日子框架，一直没有发送出log日志，这个是为什么了

### ISSUE THREAD

**Issue by itcheng** [wenmingvs/LogReport#84]
我在我的发件箱里面和我的收件箱里面。都没有看到日志发送和接受

**Comment by wenmingvs** [comment]
请运行下我的Demo，使用我写好的邮箱，看下LogCat有没有 『发送成功』 的关键字，如果有，说明我的Demo是正常的，是你的邮箱出了问题

**Comment by itcheng** [comment]
我后来试试了一下，发现是我这自己写错了，现在可以正常发送日志了，但是我想问下，我怎么LogWriter.writeLog("wenming", "打Log测试！！！！");这个里面
写的内容怎么能写在CrashLog2016-08-01文件，而不要写在MonitorLog2016-08-01里，
因为我觉得，把错误内容和自己写的调试log,写在2个文件里面，分开看，很不方便

chengchunhuiit@163.com

发件人： wenmingvs
发送时间： 2016-08-01 17:20
收件人： wenmingvs/LogReport
抄送： Android_Learner; Author
主题： Re: [wenmingvs/LogReport] 我用你的日子框架，一直没有发送出log日志，这个是为什么了 (#84)
请运行下我的Demo，使用我写好的邮箱，看下LogCat有没有 『发送成功』 的关键字，如果有，说明我的Demo是正常的，是你的邮箱出了问题

**Comment by itcheng** [comment]
方便加下我的QQ交流下么？邮件太慢了些，我的QQ：1617044578

public static void writeLog(String tag, String content) {
    LogUtil.d(tag, content);
    mSave.writeLog(tag, content);
}
能否在LogWriter类里加一个这个方法，让我可以你自己写一些crash的调试信息，到异常信息里面，一起来查看这样比较方便，多谢void writeCrash(Thread var1, Throwable var2, String var3, String var4);

chengchunhuiit@163.com

发件人： chengchunhuiit@163.com
发送时间： 2016-08-01 17:33
收件人： wenmingvs/LogReport
主题： Re: Re: [wenmingvs/LogReport] 我用你的日子框架，一直没有发送出log日志，这个是为什么了 (#84)
我后来试试了一下，发现是我这自己写错了，现在可以正常发送日志了，但是我想问下，我怎么LogWriter.writeLog("wenming", "打Log测试！！！！");这个里面
写的内容怎么能写在CrashLog2016-08-01文件，而不要写在MonitorLog2016-08-01里，
因为我觉得，把错误内容和自己写的调试log,写在2个文件里面，分开看，很不方便

chengchunhuiit@163.com

发件人： wenmingvs
发送时间： 2016-08-01 17:20
收件人： wenmingvs/LogReport
抄送： Android_Learner; Author
主题： Re: [wenmingvs/LogReport] 我用你的日子框架，一直没有发送出log日志，这个是为什么了 (#84)
请运行下我的Demo，使用我写好的邮箱，看下LogCat有没有 『发送成功』 的关键字，如果有，说明我的Demo是正常的，是你的邮箱出了问题

**Comment by wenmingvs** [comment]
已加

**Comment by itcheng** [comment]
非常感谢作者解决了我的问题！thanks
